services:
  - type: web
    name: hirehub-api
    env: python
    rootDir: api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
  - type: static_site
    name: hirehub-demo
    rootDir: web
    buildCommand: ""
    staticPublishPath: .
    envVars:
      - key: HIREHUB_API
        value: https://hirehub-api.onrender.com
