const API=(window.HIREHUB_CONFIG||{}).API_BASE||'';
const store={get token(){return localStorage.getItem('hh_token')||''},set token(v){localStorage.setItem('hh_token',v||'')}};
async function api(p,o={}){const h=Object.assign({'Content-Type':'application/json'},o.headers||{}); if(store.token)h.Authorization='Bearer '+store.token; const r=await fetch(API+p,Object.assign({},o,{headers:h})); const t=await r.text(); let j; try{j=JSON.parse(t)}catch{j={raw:t}}; if(!r.ok)throw{status:r.status,data:j}; return j}
function $(q,r=document){return r.querySelector(q)}; function $all(q,r=document){return Array.from(r.querySelectorAll(q))}
function initSidebar(){const b=$('#btnSidebar'),s=$('#sidebar'); if(b&&s){b.addEventListener('click',()=>s.classList.toggle('open')); $all('.nav-link').forEach(a=>a.addEventListener('click',()=>s.classList.remove('open')))}}
async function doRegister(){const company=$('#company').value.trim()||'CreativeCo',email=$('#email').value.trim()||'ceo@creative.co',password=$('#password').value||'test1234',out=$('#authOut'); out.textContent='Регистрирам...'; try{const r=await api('/v1/auth/register',{method:'POST',body:JSON.stringify({company_name:company,email,password})}); store.token=r.token||''; out.textContent=JSON.stringify(r,null,2)}catch(e){out.textContent='Грешка '+(e.status||'')+': '+JSON.stringify(e.data,null,2)}}
async function doLogin(){const email=$('#email').value.trim()||'ceo@creative.co',password=$('#password').value||'test1234',out=$('#authOut'); out.textContent='Влизам...'; try{const r=await api('/v1/auth/login',{method:'POST',body:JSON.stringify({email,password})}); store.token=r.token||''; out.textContent=JSON.stringify(r,null,2)}catch(e){out.textContent='Грешка '+(e.status||'')+': '+JSON.stringify(e.data,null,2)}}
async function loadMetrics(){const out=$('#metricsOut'); try{const r=await api('/v1/metrics'); out.textContent=JSON.stringify(r,null,2)}catch(e){out.textContent='Грешка: '+JSON.stringify(e.data,null,2)}}
const DEMO=[{name:'Иван Петров',role:'Account Manager',score:86,tags:['B2B','CRM','EN C1']},{name:'Мария Стоянова',role:'React Developer',score:91,tags:['React','TypeScript','EN B2']},{name:'Geert de Vries',role:'Sales Lead (NL)',score:78,tags:['Sales','Dutch','HubSpot']}];
function renderCandidates(){const tb=$('#candTbody'); if(!tb)return; tb.innerHTML=''; DEMO.forEach(c=>{const tr=document.createElement('tr'); tr.innerHTML='<td>'+c.name+'</td><td class="text-slate-600">'+c.role+'</td><td><span class="hh-badge">'+c.score+'/100</span></td><td>'+c.tags.map(t=>'<span class="hh-pill mr-1">'+t+'</span>').join('')+'</td><td><button class="hh-btn text-sm" onclick="openLuna(\''+c.name+'\', \' '+c.role+' \')">Analyze</button></td>'; tb.appendChild(tr)})}
function openLuna(n,r){const u=new URL('luna.html',location.href); u.searchParams.set('name',n); u.searchParams.set('role',r); location.href=u.toString()}
async function askLuna(){const i=$('#msg'),out=$('#lunaOut'),val=i.value.trim(); if(!val){i.focus();return} out.textContent='Luna мисли...'; try{const r=await api('/v1/luna/chat',{method:'POST',body:JSON.stringify({messages:[{role:'user',content:val}]})}); out.textContent=JSON.stringify(r,null,2)}catch(e){out.textContent='Грешка: '+JSON.stringify(e.data,null,2)}}
function initPage(){initSidebar(); if($('#authPage')){$('#btnRegister').addEventListener('click',doRegister); $('#btnLogin').addEventListener('click',doLogin)} if($('#dashPage')){loadMetrics(); renderCandidates()} if($('#lunaPage')){const p=new URLSearchParams(location.search); const n=p.get('name'), r=p.get('role'); if(n||r) $('#msg').value='Кандидат: '+(n||'')+', роля: '+(r||'')+'. Направи кратък анализ.'; $('#btnAskLuna').addEventListener('click',askLuna)}}
document.addEventListener('DOMContentLoaded',initPage);